### ISSUE TITLE
Options for faster development

### ISSUE THREAD

**Issue by vvvvalvalval** [pointslope/boot-fingerprint#2]
I have found that fingerprinting assets takes most of the reload time when I develop with it. It would be nice to make it faster.

Let me suggest 2 possible improvements:
1. **Podless mode:** add an option to not process the files in a separate pod, this avoiding the pod creation overhead
2. **Noop flag:** add an option to skip the computation of the file hashes.

What do you think?

**Comment by ddeaguiar** [comment]
I think a noop flag is a good idea. I think podless mode is worth exploring not just for performance reasons, but for task simplification. Thanks for the feedback!

**Comment by ddeaguiar** [comment]
@vvvvalvalval take a look at the latest changes and tell me what you think. They're available on [clojars](https://clojars.org/boot-fingerprint/versions/0.1.1-SNAPSHOT) with the '0.1.1-SNAPSHOT'. I don't skip fingerprinting entirely, however. I think it would be best to replace the vars with their values so that the html files don't have to be manually updated.

**Comment by vvvvalvalval** [comment]
Thanks, it got way faster! I think most of the performance improvement came from the podless mode. However, if other task authors use this design, maybe we should check what the benefits of encapsulating task execution in a pod are (my guess is that it offers better guarantees on the version of the dependencies used by the task - in your case Enlive). 
And of course, you're right about not skipping the whole processing - variable replacement has to be done.

**Comment by ddeaguiar** [comment]
I'm going to close this ticket. I'll think about supported pods in the future.
